//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo3.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order_Products = new HashSet<Order_Products>();
        }
    
        public int ID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int ID_Measurement { get; set; }
        public decimal Price { get; set; }
        public int ID_Supplier { get; set; }
        public int ID_Manufacturer { get; set; }
        public int ID_Category { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int Quantity { get; set; }
        public string Desc { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual ICollection<Order_Products> Order_Products { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
