//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int ID_City { get; set; }
        public string Name { get; set; }
        public int HomeNumber { get; set; }
        public int Index { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
