//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Products = new HashSet<Order_Products>();
        }
    
        public int ID { get; set; }
        public System.DateTime? OrderDate { get; set; }
        public System.DateTime? ShipmentDate { get; set; }
        public int ID_Address { get; set; }
        public int ID_User { get; set; }
        public int Code { get; set; }
        public int ID_Status { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Order_Products> Order_Products { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
